/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiSawaalRouteImport } from './routes/ai-sawaal'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as BikriRouteImport } from './routes/bikri'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DailyClosingRouteImport } from './routes/daily-closing'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as HeldCartsRouteImport } from './routes/held-carts'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as HisaabRouteImport } from './routes/hisaab'
import { Route as KharchaRouteImport } from './routes/kharcha'
import { Route as KharidRouteImport } from './routes/kharid'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as UdhaarRouteImport } from './routes/udhaar'
import { Route as WapsiRouteImport } from './routes/wapsi'
import { Route as SamaanIndexRouteImport } from './routes/samaan.index'
import { Route as SamaanIdRouteImport } from './routes/samaan.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSawaalRoute = AiSawaalRouteImport.update({
  id: '/ai-sawaal',
  path: '/ai-sawaal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const BikriRoute = BikriRouteImport.update({
  id: '/bikri',
  path: '/bikri',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyClosingRoute = DailyClosingRouteImport.update({
  id: '/daily-closing',
  path: '/daily-closing',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const HeldCartsRoute = HeldCartsRouteImport.update({
  id: '/held-carts',
  path: '/held-carts',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HisaabRoute = HisaabRouteImport.update({
  id: '/hisaab',
  path: '/hisaab',
  getParentRoute: () => rootRouteImport,
} as any)
const KharchaRoute = KharchaRouteImport.update({
  id: '/kharcha',
  path: '/kharcha',
  getParentRoute: () => rootRouteImport,
} as any)
const KharidRoute = KharidRouteImport.update({
  id: '/kharid',
  path: '/kharid',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const UdhaarRoute = UdhaarRouteImport.update({
  id: '/udhaar',
  path: '/udhaar',
  getParentRoute: () => rootRouteImport,
} as any)
const WapsiRoute = WapsiRouteImport.update({
  id: '/wapsi',
  path: '/wapsi',
  getParentRoute: () => rootRouteImport,
} as any)
const SamaanIndexRoute = SamaanIndexRouteImport.update({
  id: '/samaan/',
  path: '/samaan/',
  getParentRoute: () => rootRouteImport,
} as any)
const SamaanIdRoute = SamaanIdRouteImport.update({
  id: '/samaan/$id',
  path: '/samaan/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-sawaal': typeof AiSawaalRoute
  '/audit-log': typeof AuditLogRoute
  '/bikri': typeof BikriRoute
  '/customers': typeof CustomersRoute
  '/daily-closing': typeof DailyClosingRoute
  '/debug': typeof DebugRoute
  '/held-carts': typeof HeldCartsRoute
  '/guide': typeof GuideRoute
  '/hisaab': typeof HisaabRoute
  '/kharcha': typeof KharchaRoute
  '/kharid': typeof KharidRoute
  '/notifications': typeof NotificationsRoute
  '/receipts': typeof ReceiptsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/suppliers': typeof SuppliersRoute
  '/udhaar': typeof UdhaarRoute
  '/wapsi': typeof WapsiRoute
  '/samaan/$id': typeof SamaanIdRoute
  '/samaan/': typeof SamaanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-sawaal': typeof AiSawaalRoute
  '/audit-log': typeof AuditLogRoute
  '/bikri': typeof BikriRoute
  '/customers': typeof CustomersRoute
  '/daily-closing': typeof DailyClosingRoute
  '/held-carts': typeof HeldCartsRoute
  '/hisaab': typeof HisaabRoute
  '/kharcha': typeof KharchaRoute
  '/kharid': typeof KharidRoute
  '/notifications': typeof NotificationsRoute
  '/receipts': typeof ReceiptsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/suppliers': typeof SuppliersRoute
  '/udhaar': typeof UdhaarRoute
  '/wapsi': typeof WapsiRoute
  '/samaan/$id': typeof SamaanIdRoute
  '/samaan': typeof SamaanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-sawaal': typeof AiSawaalRoute
  '/audit-log': typeof AuditLogRoute
  '/bikri': typeof BikriRoute
  '/customers': typeof CustomersRoute
  '/daily-closing': typeof DailyClosingRoute
  '/held-carts': typeof HeldCartsRoute
  '/hisaab': typeof HisaabRoute
  '/kharcha': typeof KharchaRoute
  '/kharid': typeof KharidRoute
  '/notifications': typeof NotificationsRoute
  '/receipts': typeof ReceiptsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/suppliers': typeof SuppliersRoute
  '/udhaar': typeof UdhaarRoute
  '/wapsi': typeof WapsiRoute
  '/samaan/$id': typeof SamaanIdRoute
  '/samaan/': typeof SamaanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-sawaal'
    | '/audit-log'
    | '/bikri'
    | '/customers'
    | '/daily-closing'
    | '/debug'
    | '/held-carts'
    | '/guide'
    | '/hisaab'
    | '/kharcha'
    | '/kharid'
    | '/notifications'
    | '/receipts'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/suppliers'
    | '/udhaar'
    | '/wapsi'
    | '/samaan/$id'
    | '/samaan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-sawaal'
    | '/audit-log'
    | '/bikri'
    | '/customers'
    | '/daily-closing'
    | '/held-carts'
    | '/hisaab'
    | '/kharcha'
    | '/kharid'
    | '/notifications'
    | '/receipts'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/suppliers'
    | '/udhaar'
    | '/wapsi'
    | '/samaan/$id'
    | '/samaan'
  id:
    | '__root__'
    | '/'
    | '/ai-sawaal'
    | '/audit-log'
    | '/bikri'
    | '/customers'
    | '/daily-closing'
    | '/held-carts'
    | '/hisaab'
    | '/kharcha'
    | '/kharid'
    | '/notifications'
    | '/receipts'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/suppliers'
    | '/udhaar'
    | '/wapsi'
    | '/samaan/$id'
    | '/samaan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiSawaalRoute: typeof AiSawaalRoute
  AuditLogRoute: typeof AuditLogRoute
  BikriRoute: typeof BikriRoute
  CustomersRoute: typeof CustomersRoute
  DailyClosingRoute: typeof DailyClosingRoute
  HeldCartsRoute: typeof HeldCartsRoute
  HisaabRoute: typeof HisaabRoute
  KharchaRoute: typeof KharchaRoute
  KharidRoute: typeof KharidRoute
  NotificationsRoute: typeof NotificationsRoute
  ReceiptsRoute: typeof ReceiptsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  SuppliersRoute: typeof SuppliersRoute
  UdhaarRoute: typeof UdhaarRoute
  WapsiRoute: typeof WapsiRoute
  SamaanIdRoute: typeof SamaanIdRoute
  SamaanIndexRoute: typeof SamaanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-sawaal': {
      id: '/ai-sawaal'
      path: '/ai-sawaal'
      fullPath: '/ai-sawaal'
      preLoaderRoute: typeof AiSawaalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bikri': {
      id: '/bikri'
      path: '/bikri'
      fullPath: '/bikri'
      preLoaderRoute: typeof BikriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-closing': {
      id: '/daily-closing'
      path: '/daily-closing'
      fullPath: '/daily-closing'
      preLoaderRoute: typeof DailyClosingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/held-carts': {
      id: '/held-carts'
      path: '/held-carts'
      fullPath: '/held-carts'
      preLoaderRoute: typeof HeldCartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hisaab': {
      id: '/hisaab'
      path: '/hisaab'
      fullPath: '/hisaab'
      preLoaderRoute: typeof HisaabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kharcha': {
      id: '/kharcha'
      path: '/kharcha'
      fullPath: '/kharcha'
      preLoaderRoute: typeof KharchaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kharid': {
      id: '/kharid'
      path: '/kharid'
      fullPath: '/kharid'
      preLoaderRoute: typeof KharidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/udhaar': {
      id: '/udhaar'
      path: '/udhaar'
      fullPath: '/udhaar'
      preLoaderRoute: typeof UdhaarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wapsi': {
      id: '/wapsi'
      path: '/wapsi'
      fullPath: '/wapsi'
      preLoaderRoute: typeof WapsiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samaan/': {
      id: '/samaan/'
      path: '/samaan'
      fullPath: '/samaan/'
      preLoaderRoute: typeof SamaanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samaan/$id': {
      id: '/samaan/$id'
      path: '/samaan/$id'
      fullPath: '/samaan/$id'
      preLoaderRoute: typeof SamaanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiSawaalRoute: AiSawaalRoute,
  AuditLogRoute: AuditLogRoute,
  BikriRoute: BikriRoute,
  CustomersRoute: CustomersRoute,
  DailyClosingRoute: DailyClosingRoute,
  DebugRoute: DebugRoute,
  HeldCartsRoute: HeldCartsRoute,
  GuideRoute: GuideRoute,
  HisaabRoute: HisaabRoute,
  KharchaRoute: KharchaRoute,
  KharidRoute: KharidRoute,
  NotificationsRoute: NotificationsRoute,
  ReceiptsRoute: ReceiptsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  SuppliersRoute: SuppliersRoute,
  UdhaarRoute: UdhaarRoute,
  WapsiRoute: WapsiRoute,
  SamaanIdRoute: SamaanIdRoute,
  SamaanIndexRoute: SamaanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
